<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestCaseMM" nsURI="www.ehu.eus/sgi/testcase" nsPrefix="tsc">
  <eClassifiers xsi:type="ecore:EClass" name="Testcase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usr" lowerBound="1" eType="#//User"
        containment="true" eOpposite="#//User/tc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wp" lowerBound="1" eType="#//WebPage"
        containment="true" eOpposite="#//WebPage/tc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tc" lowerBound="1" eType="#//Testcase"
        eOpposite="#//Testcase/usr"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tc" lowerBound="1" eType="#//Testcase"
        eOpposite="#//Testcase/wp"/>
  </eClassifiers>
</ecore:EPackage>
